name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # -- WINDOWS ------------------------------------
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B build -G "Visual Studio 17 2022" -A x64

      - name: Build Debug
        run: cmake --build build --config Debug -- /m

      - name: Run Debug headless
        run: ./build/Debug/Game.exe --headless

      - name: Build Release
        run: cmake --build build --config Release -- /m

      - name: Run Release headless
        run: ./build/Release/Game.exe --headless

  # -- MAC -------------------------------------
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Configure CMake
        run: |
          cmake -B build \
            -G "Xcode" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14

      - name: Build Debug
        run: cmake --build build --config Debug

      - name: Run Debug headless
        run: ./build/Debug/Game --headless

      - name: Build Release
        run: cmake --build build --config Release

      - name: Run Release headless
        run: ./build/Release/Game --headless

  # -- LINUX -------------------------------------------
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libwayland-dev \
            wayland-protocols \
            libxkbcommon-dev \
            pkg-config

      - name: Install virtual display
        run: sudo apt-get install -y xvfb

      - name: Build Debug
        run: |
          cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Debug
          cmake --build build

      - name: Run Debug headless
        run: xvfb-run ./build/Game --headless

      - name: Build Release
        run: |
          cmake -B build-release -G "Ninja" -DCMAKE_BUILD_TYPE=Release
          cmake --build build-release

      - name: Run Release headless
        run: xvfb-run ./build-release/Game --headless